/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : phy_cfg.c
**     Project     : sja1105smbevm_tc10example
**     Processor   : MPC5748G_256
**     Component   : phy
**     Version     : Component SDK_S32_PA_11, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_11
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-07-11, 10:21, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file phy_cfg.c                                                  
** @version 01.00
*/         
/*!
**  @addtogroup phy_cfg_module phy_cfg module documentation
**  @{
*/         

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * The symbol is defined to be used by the application code.
 *
 */
 
#include "phy_cfg.h"

#define PHY_TYPE_GENERIC (0U)
#define PHY_TYPE_TJA110X (1U)

/*! @brief Array of pointers towards the driver structures */
phy_driver_t* phyDrivers[N_PHY_DRIVERS] = {&PHY_driver_generic, &PHY_driver_tja110x};

/*! @brief Array of PHY configuration structures */
phy_config_t  phyConfig[N_PHY_DEVS] = {
    {
        .type = PHY_TYPE_GENERIC,
        .addr = 1,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_AUTONEG,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_AUTO,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = NULL,
        .autonegFailedCB = NULL,
        .extendedConfig = NULL
    },
    {
        .type = PHY_TYPE_GENERIC,
        .addr = 2,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_AUTONEG,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_AUTO,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = phy_callbacks_autonegCompleteCB,
        .autonegFailedCB = phy_callbacks_autonegFailedCB,
        .extendedConfig = NULL
    },
    {
        .type = PHY_TYPE_GENERIC,
        .addr = 3,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_AUTONEG,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_AUTO,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = phy_callbacks_autonegCompleteCB,
        .autonegFailedCB = phy_callbacks_autonegFailedCB,
        .extendedConfig = NULL
    },
    {
        .type = PHY_TYPE_TJA110X,
        .addr = 4,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_100_MBPS,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_SLAVE,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = NULL,
        .autonegFailedCB = NULL,
        .extendedConfig = NULL
    },
    {
        .type = PHY_TYPE_TJA110X,
        .addr = 6,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_100_MBPS,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_SLAVE,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = NULL,
        .autonegFailedCB = NULL,
        .extendedConfig = NULL
    },
    {
        .type = PHY_TYPE_TJA110X,
        .addr = 7,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_100_MBPS,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_SLAVE,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = NULL,
        .autonegFailedCB = NULL,
        .extendedConfig = NULL
    },
    {
        .type = PHY_TYPE_TJA110X,
        .addr = 8,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_100_MBPS,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_SLAVE,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = NULL,
        .autonegFailedCB = NULL,
        .extendedConfig = NULL
    },
    {
        .type = PHY_TYPE_TJA110X,
        .addr = 9,
        .enetInstance = 0,
        .clause45 = false,
        .speed = PHY_SPEED_100_MBPS,
        .location = PHY_LOCATION_EXTERNAL,
        .role = PHY_ROLE_SLAVE,
        .linkUpEventCB = phy_callbacks_linkUpEventCB,
        .linkDownEventCB = phy_callbacks_linkDownEventCB,
        .sleepRequestCB = NULL,
        .autonegCompleteCB = NULL,
        .autonegFailedCB = NULL,
        .extendedConfig = NULL
    },
};

/* END phy. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
