/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : spi_sw.h
**     Project     : sja1105smbevm_tc10example
**     Processor   : MPC5748G_256
**     Component   : dspi
**     Version     : Component SDK_S32_PA_11, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_11
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-07-11, 10:21, # CodeGen: 0
**     Contents    :
**         DSPI_MasterSetDelay         - status_t DSPI_MasterSetDelay(dspi_instance_t instance,uint32_t...
**         DSPI_GetDefaultMasterCfg    - status_t DSPI_GetDefaultMasterCfg(dspi_master_config_t * config);
**         DSPI_MasterInit             - status_t DSPI_MasterInit(dspi_instance_t instance,dspi_state_t * state,const...
**         DSPI_MasterTransfer         - status_t DSPI_MasterTransfer(dspi_instance_t instance,void * sendBuffer,void...
**         DSPI_MasterTransferBlocking - status_t DSPI_MasterTransferBlocking(dspi_instance_t instance,void *...
**         DSPI_AbortTransfer          - status_t DSPI_AbortTransfer(dspi_instance_t instance);
**         DSPI_UpdateCS               - status_t DSPI_UpdateCS(dspi_instance_t instance,uint8_t whichPCS);
**         DSPI_GetDefaultSlaveCfg     - status_t DSPI_GetDefaultSlaveCfg(dspi_slave_config_t * config);
**         DSPI_SlaveInit              - status_t DSPI_SlaveInit(dspi_instance_t instance,dspi_state_t * state,const...
**         DSPI_SlaveTransfer          - status_t DSPI_SlaveTransfer(dspi_instance_t instance,void * sendBuffer,void *...
**         DSPI_SlaveTransferBlocking  - status_t DSPI_SlaveTransferBlocking(dspi_instance_t instance,void *...
**         DSPI_Deinit                 - status_t DSPI_Deinit(dspi_instance_t instance);
**         DSPI_GetTransferStatus      - status_t DSPI_GetTransferStatus(dspi_instance_t...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file spi_sw.h
** @version 01.00
*/         
/*!
**  @addtogroup spi_sw_module spi_sw module documentation
**  @{
*/         
#ifndef spi_sw_H
#define spi_sw_H
/* MODULE spi_sw. */

/*!
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The macros defined are used to define features for each driver, so this might be reported
 * when the analysis is made only on one driver.
 *
 */

 /* Include inherited beans */
#include "dspi_driver.h" 
#include "clockMan.h"
#include "dmaController1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define INST_SPI_SW (5U)
/*! @brief Driver state structure which holds driver runtime data */
extern dspi_state_t spi_swState; 
/*! @brief Module configuration structures */
/*! @brief Master module configurations */
extern dspi_master_config_t spi_sw_0;
extern dspi_master_config_t spi_sw_1;
/*! @brief Slave module configurations */
/*! @brief Define external callbacks for slave devices */
/*! @brief Define external callbacks for master devices */

#endif
/* ifndef spi_sw_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

